clc;clear;
I=imread('Test.jpg');
I=uint8(I(1:400,1:626,1:3));
subplot(2,2,1)
imshow(I);
%%
r=I(:,:,1);
g=I(:,:,2);
b=I(:,:,3);
%%
%根据颜色索引该小车区域
r1=r>180&r<255;
g1=g>50&g<130;
b1=b>55&b<140;
im_con=r1.*g1.*b1;
subplot(2,2,2)
imshow(im_con);
%%
%观察到有两个区域符合要求
im=bwconncomp(im_con);
s=im.PixelIdxList{1};
%%
%重建区域
im_box=zeros(size(r));
im_box(s)=1;
subplot(2,2,3)
imshow(im_box);
%%
[row,col]=find(im_box);
minrow=min(row);
maxrow=max(row);
mincol=min(col);
maxcol=max(col);
subplot(2,2,4)
imshow(I(minrow:maxrow,mincol:maxcol,1:3));